const STORAGE_KEY = 'ccp-course-hub-data';
let data;
const $ = (selector, scope = document) => scope.querySelector(selector);
const esc = (value = '') => String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
const slug = value => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function loadData() { const stored = localStorage.getItem(STORAGE_KEY); if (stored) return JSON.parse(stored); const response = await fetch('../data.json'); return response.json(); }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); render(); }
function download() { const file = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(file); link.download = 'data.json'; link.click(); URL.revokeObjectURL(link.href); }
function list(items, title, meta, kind) { return items.length ? `<div class="list">${items.map((item, index) => `<div class="list-item"><div><strong>${esc(title(item))}</strong><br><span>${esc(meta(item))}</span></div><div><button data-edit="${kind}" data-index="${index}">Edit</button><button data-delete="${kind}" data-index="${index}">Delete</button></div></div>`).join('')}</div>` : '<p class="count">No content added yet.</p>'; }
function card(title, description, body, kind) { return `<section class="editor-card"><h2>${title}</h2><p>${description}</p>${body}<div class="actions"><button class="button" data-add="${kind}">+ Add ${title.replace(/s$/, '')}</button></div></section>`; }
function render() {
  $('#editor').innerHTML = `
    <section class="editor-card wide"><h2>Publishing controls</h2><p>Preview changes in the public hub on this device, or export the updated content file for GitHub.</p><div class="actions"><button class="button" data-action="export">Export data.json</button><button class="button secondary" data-action="json">Edit complete data source</button><button class="button secondary" data-action="reset">Discard local changes</button></div></section>
    ${card('Weeks', 'Create, edit and reorder the semester timeline.', list(data.schedule, item => `Week ${item.week}: ${item.title}`, item => item.dateRange, 'week'), 'week')}
    ${card('Guest Lecturers', 'Profiles, lecture content and contact links.', list(data.guestLecturers, item => item.name, item => `${item.role} · ${item.company}`, 'guest'), 'guest')}
    ${card('Portfolio Briefs', 'Self-initiated projects students can browse and expand.', list(data.portfolioBriefs, item => item.title, item => item.category, 'brief'), 'brief')}
    ${card('Group Scenarios', 'Briefs for the collaborative project.', list(data.groupProject.scenarios, item => item.title, item => item.category, 'scenario'), 'scenario')}
    ${card('Resources', 'Downloads, links, templates and course materials.', list(data.resources, item => item.title, item => item.category, 'resource'), 'resource')}
    ${card('Announcements', 'Create and pin course updates.', list(data.announcements, item => item.title, item => item.date, 'announcement'), 'announcement')}
    <section class="editor-card wide"><h2>Course settings</h2><p>Course introduction, feedback contact and booking link.</p><div class="actions"><button class="button" data-action="course">Edit course settings</button><button class="button secondary" data-action="group">Edit group project overview</button><button class="button secondary" data-action="portfolio">Edit final portfolio overview</button></div></section>`;
}
const field = (name, label, value = '', type = 'text', options = '') => `<label>${label}${type === 'textarea' ? `<textarea name="${name}">${esc(value)}</textarea>` : type === 'select' ? `<select name="${name}">${options}</select>` : `<input name="${name}" type="${type}" value="${esc(value)}">`}</label>`;
function modal(title, content, onSubmit) { document.body.insertAdjacentHTML('beforeend', `<div class="modal"><div class="modal-box"><button class="modal-close" aria-label="Close">×</button><h2>${title}</h2><form>${content}<div class="form-actions"><button class="button secondary" type="button" data-cancel>Cancel</button><button class="button" type="submit">Save changes</button></div></form></div></div>`); const box = $('.modal'); $('form', box).addEventListener('submit', event => { event.preventDefault(); onSubmit(Object.fromEntries(new FormData(event.currentTarget))); box.remove(); save(); }); }
function csv(value = '') { return value.split(',').map(item => item.trim()).filter(Boolean); }
function forms(kind, existing = {}) {
  if (kind === 'week') return { title: existing.week ? 'Edit week' : 'Add week', html: `<div class="form-grid">${field('week','Week number',existing.week || data.schedule.length + 1,'number')}${field('dateRange','Date range',existing.dateRange)}</div>${field('title','Week title',existing.title)}<label>Schedule items (one JSON object per line)<textarea name="events">${esc((existing.events || []).map(item => JSON.stringify(item)).join('\n'))}</textarea></label>`, apply: values => ({ week:Number(values.week), title:values.title, dateRange:values.dateRange, events:values.events.trim() ? values.events.trim().split('\n').map(line => JSON.parse(line)) : [] }) };
  if (kind === 'guest') return { title: existing.name ? 'Edit guest lecturer' : 'Add guest lecturer', html: `${field('name','Name',existing.name)}<div class="form-grid">${field('role','Role',existing.role)}${field('company','Company',existing.company)}</div>${field('portrait','Portrait image path or URL',existing.portrait)}${field('bio','Biography',existing.bio,'textarea')}${field('lectureTitle','Lecture title',existing.lectureTitle)}${field('lectureDescription','Lecture description',existing.lectureDescription,'textarea')}${field('learningOutcomes','Learning outcomes (comma separated)',(existing.learningOutcomes || []).join(', '))}<div class="form-grid">${field('date','Date',existing.date)}${field('time','Time',existing.time)}</div>${field('room','Room',existing.room)}<div class="form-grid">${field('website','Website',existing.website)}${field('instagram','Instagram',existing.instagram)}</div>${field('linkedin','LinkedIn',existing.linkedin)}<label><input name="featured" type="checkbox" ${existing.featured ? 'checked' : ''}> Featured on dashboard</label>`, apply: values => ({...existing,id:existing.id || slug(values.name),...values,featured:values.featured === 'on',learningOutcomes:csv(values.learningOutcomes)}) };
  if (kind === 'brief') return { title: existing.title ? 'Edit portfolio brief' : 'Add portfolio brief', html: `${field('title','Title',existing.title)}<div class="form-grid">${field('category','Category',existing.category)}${field('difficulty','Difficulty',existing.difficulty)}</div>${field('shortDescription','Short description',existing.shortDescription,'textarea')}${field('description','Full brief description',existing.description,'textarea')}${field('client','Client',existing.client)}${field('background','Background',existing.background,'textarea')}${field('challenge','Challenge',existing.challenge,'textarea')}${field('goals','Goals (comma separated)',(existing.goals || []).join(', '))}${field('audience','Audience',existing.audience)}${field('creativeFreedom','Creative freedom',existing.creativeFreedom,'textarea')}${field('portfolioValue','Portfolio value',existing.portfolioValue,'textarea')}<div class="form-grid">${field('skills','Skills (comma separated)',(existing.skills || []).join(', '))}${field('workload','Estimated workload',existing.workload)}</div>${field('image','Image path or URL',existing.image)}`, apply: values => ({...existing,id:existing.id || slug(values.title),...values,goals:csv(values.goals),skills:csv(values.skills)}) };
  if (kind === 'scenario') return { title: existing.title ? 'Edit group scenario' : 'Add group scenario', html: `${field('title','Title',existing.title)}<div class="form-grid">${field('category','Category',existing.category)}${field('workload','Estimated workload',existing.workload)}</div>${field('shortDescription','Short description',existing.shortDescription,'textarea')}${field('brief','Full brief',existing.brief,'textarea')}${field('skills','Skills developed (comma separated)',(existing.skills || []).join(', '))}`, apply: values => ({...existing,id:existing.id || slug(values.title),...values,skills:csv(values.skills)}) };
  if (kind === 'resource') return { title: existing.title ? 'Edit resource' : 'Add resource', html: `${field('title','Title',existing.title)}<div class="form-grid">${field('category','Category',existing.category)}${field('icon','Icon character',existing.icon || '↗')}</div>${field('description','Description',existing.description,'textarea')}${field('url','Download or external URL',existing.url)}`, apply: values => ({...existing,id:existing.id || slug(values.title),...values}) };
  if (kind === 'announcement') return { title: existing.title ? 'Edit announcement' : 'Add announcement', html: `${field('title','Title',existing.title)}${field('body','Announcement',existing.body,'textarea')}<div class="form-grid">${field('date','Date',existing.date)}<label><input name="pinned" type="checkbox" ${existing.pinned ? 'checked' : ''}> Pin to dashboard</label></div>`, apply: values => ({...existing,id:existing.id || slug(values.title),...values,pinned:values.pinned === 'on'}) };
}
function collection(kind) { return kind === 'scenario' ? data.groupProject.scenarios : kind === 'week' ? data.schedule : kind === 'guest' ? data.guestLecturers : kind === 'brief' ? data.portfolioBriefs : kind === 'resource' ? data.resources : data.announcements; }
function openEditor(kind, index) { const items = collection(kind); const existing = Number.isInteger(index) ? items[index] : {}; const config = forms(kind, existing); modal(config.title, config.html, values => { const next = config.apply(values); if (Number.isInteger(index)) items[index] = next; else items.push(next); if (kind === 'week') items.sort((a,b) => a.week - b.week); }); }
function editSettings(type) {
  const target = type === 'course' ? data.course : type === 'group' ? data.groupProject : data.finalPortfolio;
  const keys = type === 'course' ? [['title','Course title'],['term','Term'],['welcome','Welcome headline'],['description','Introduction'],['feedbackEmail','Feedback email'],['bookingUrl','Outlook Booking URL']] : type === 'group' ? [['overview','Overview'],['timeline','Timeline (one item per line)'],['deliverables','Deliverables (one item per line)'],['assessment','Assessment']] : [['overview','Overview'],['structure','Portfolio structure (one item per line)'],['submission','Submission'],['assessment','Assessment']];
  const html = keys.map(([key,label]) => Array.isArray(target[key]) ? field(key,label,target[key].join('\n'),'textarea') : field(key,label,target[key],key === 'overview' || key === 'description' || key === 'assessment' || key === 'submission' ? 'textarea' : 'text')).join('');
  modal(`Edit ${type === 'course' ? 'course settings' : type === 'group' ? 'group project' : 'final portfolio'}`, html, values => keys.forEach(([key]) => { target[key] = Array.isArray(target[key]) ? values[key].split('\n').map(item => item.trim()).filter(Boolean) : values[key]; }));
}
document.addEventListener('click', event => {
  if (event.target.matches('.modal-close, [data-cancel], .modal')) { if (event.target.matches('.modal') || event.target.matches('.modal-close, [data-cancel]')) $('.modal')?.remove(); return; }
  const add = event.target.closest('[data-add]'); if (add) openEditor(add.dataset.add);
  const edit = event.target.closest('[data-edit]'); if (edit) openEditor(edit.dataset.edit, Number(edit.dataset.index));
  const remove = event.target.closest('[data-delete]'); if (remove && confirm('Delete this item?')) { collection(remove.dataset.delete).splice(Number(remove.dataset.index), 1); save(); }
  const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'export') download(); if (action === 'json') modal('Edit complete data source', `<label>data.json<textarea name="json">${esc(JSON.stringify(data, null, 2))}</textarea></label>`, values => { data = JSON.parse(values.json); }); if (action === 'reset' && confirm('Discard all local editor changes?')) { localStorage.removeItem(STORAGE_KEY); location.reload(); } if (['course','group','portfolio'].includes(action)) editSettings(action);
});
loadData().then(loaded => { data = loaded; render(); }).catch(error => { $('#editor').textContent = `Could not load content: ${error.message}`; });
